inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Lint/AssignmentInCondition:
  Enabled: false

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 120

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
