#!/usr/bin/env ruby

require 'dvd_ripper'
require "thor"

module DvdRipper
  class Cli < ::Thor
    desc "start", "start tool"
    def start
      check_config!
      dvd_ripper = ::DvdRipper::Client.new
      dvd_ripper.start
    end
    map %w[--version -v] => :__print_version

    desc "--version, -v", "print the version"
    def __print_version
      puts "DvdRipper v#{::DvdRipper::VERSION}"
    end

    desc "config", "configure dvd_ripper"
    def config
      Config.instance.prompt!
    end

    desc "help", "display this help"
    def help_banner
      puts <<-BANNER
        Dvd Ripper

        This commandline utility cleanly and simply captures your dvd contents and
        tags the movies.

        Movie information is pulled from www.imdb.com and www.themoviedb.org

        Dvd content captured using Handbrake (https://handbrake.fr/)
      BANNER
      help
    end

    no_commands do
      def check_config!
        unless Config.instance.exists?
          config
        end
      end
    end

    # "www.themoviedb.org"

  end
end

::DvdRipper::Cli.start
